name: Preview Build
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  preview-build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.number }} > pr-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 10

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build playground
        run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: playground
          path: playground/dist
          retention-days: 10