name: Preview Build & Publish
on:
  pull_request:
    branches: [dev, main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "lts/*" }
      - uses: pnpm/action-setup@v4
        with: { version: latest }
      - run: pnpm install
      - name: Check CI environment
        run: |
          echo "CI=$CI"
          echo "NODE_ENV=$NODE_ENV"
          echo "GitHub Actions sets CI automatically: $CI"
      - run: pnpm build
      - name: Deploy
        id: deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          export DEPLOY_DOMAIN="https://preview-pr-${{ github.event.number }}-nordstjerna.surge.sh"
          # playground/.output/public 下是构建结果
          npx surge --project ./playground/.output/public --domain "$DEPLOY_DOMAIN"
          echo "url=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT
      - name: Comment success
        if: success()
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          body-include: "<!-- AUTO_PREVIEW_HOOK -->"
          body: |
            ### [【预览链接】](${{ steps.deploy.outputs.url }}/index.html)

            <!-- AUTO_PREVIEW_HOOK -->
      - name: Comment failure
        if: failure()
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          body-include: "<!-- AUTO_PREVIEW_HOOK -->"
          body: |
            预览编译失败
            <!-- AUTO_PREVIEW_HOOK -->
